openbank.datasource:
  url: jdbc:mysql://openbankdb:3306/openbank
  username: openbank_user
  password: ENC(DSQpSyewyvrR8AurZvZC0DUax5oSZSqRvGmcAVFwKGcTZTnshKQiTw==)
  driverclassname: com.mysql.cj.jdbc.Driver

security.datasource:
  url: jdbc:mysql://securitydb:3306/security
  username: security_user
  password: ENC(vNq9+oOFXPNeXnQwwcPWWjMCgjNMOS5z2tt1TkE7WVxXK4bib+K8/w==)
  driverclassname: com.mysql.cj.jdbc.Driver

server.port: 8443
server.ssl.key-store-type: PKCS12
server.ssl.key-store: classpath:ssl/keystore/jsquad.pfx
server.ssl.key-store-password: ENC(M5JhYsUTMq6n1OKArpvF+TvuBjQTDO+/)
server.ssl.enabled: true

world.webclient.baseUrl: https://worldapi:1080

management.endpoint.metrics.enabled: true

management.endpoints:
  web.exposure.include: 'shallow-system-status,deep-system-status,prometheus'
  prometheus.enabled: true

management.metrics.export.prometheus.enabled: true